### Variables
@apiUrl = http://localhost:5555/api
@code = {{employeeCode.response.body.code}}

### Health Check
GET {{apiUrl}}/health

### Generate Employee Code
# @name employeeCode
POST {{apiUrl}}/employee/generate-code

### Employee Log
POST {{apiUrl}}/employee
Content-Type: application/json

{
  "employeeCode": "{{code}}"
}
