### Variables
@apiUrl = http://localhost:5555/api
@code = {{employeeCode.response.body.code}}

### Health Check
GET {{apiUrl}}/health

### Generate Employee Code
# @name employeeCode
POST {{apiUrl}}/employee/generate-code

### Employee Log
POST {{apiUrl}}/employee
Content-Type: application/json

{
  "employeeCode": "{{code}}"
}

### Work Shift Entry Time
POST {{apiUrl}}/work-shift/entry-time
Content-Type: application/json

{
  "employeeCode": "{{code}}"
}

###

### Work Shift Exit Time
POST {{apiUrl}}/work-shift/exit-time
Content-Type: application/json

{
  "employeeCode": "{{code}}"
}

###